# Site settings
title: Eddy Parris
email: eddy@parr.is
description: "Stuff by Edd Parris"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://eddy.parr.is" # the base hostname & protocol for your site
twitter_username: empika
github_username:  empika
google_analytics: "UA-33574019-1"
animated: true

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3